services:
  mysql:
    image: mysql:8.4
    container_name: avalon-mysql
    restart: always
    environment:
      MYSQL_DATABASE: avalon_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - avalon_mysql_data:/var/lib/mysql

  redis:
    image: redis:7.0-alpine
    container_name: avalon-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  avalon_mysql_data:
